language: perl
perl:
  - 5.14
  - 5.16
  - 5.18
before_install:
  - cpanm --quiet --notest Test::mysqld git://github.com/kan/coveralls-perl.git git://github.com/UCormorant/p5-teng-plugin-dbic-resultset.git
script: perl Build.PL && ./Build testcover
after_success:
  - cover -report coveralls
