---
abstract: "[One line description of module's purpose here]"
author:
  - 'U=Cormorant  C<< <u@chimata.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Uc-Model-Twitter
no_index:
  directory:
    - example
    - inc
    - t
    - xt
requires:
  DateTime::Format::HTTP: 0
  DateTime::Format::MySQL: 0
  Teng: 0
  Uc::Teng::Plugin: 1.000
  perl: 5.12.0
resources:
  license: http://dev.perl.org/licenses/
  repository: origin
version: v1.0.0
