=pod

=encoding utf8

=head1 Name

Uc::Twetter::Schema - Twitter DBIx::Class for me

=head1 Synopsis

[ REPLACE THIS...

  The README is used to introduce the module and provide instructions on
  how to install the module, any machine dependencies it may have (for
  example C compilers and installed libraries) and any other information
  that should be understood before the module is installed.

  A README file is required for CPAN modules since CPAN extracts the
  README file from a module distribution so that people browsing the
  archive can use it get an idea of the modules uses. It is usually a
  good idea to provide version information here so that people can
  decide whether fixes for the module are worth downloading.
]

=head1 Installation

To install this module, run the following commands:

  perl Makefile.PL
  make
  make test
  make install

Alternatively, to install with Module::Build, you can use the following commands:

  perl Build.PL
  ./Build
  ./Build test
  ./Build install

=head1 Dependencies

=over 2

=item L<perl> >= 5.10

=item L<common::sense>

=item L<DBIx::Class>

=item L<DateTime::Format::HTTP>

=item L<DateTime::Format::MySQL>

=back

=head1 Author

L<http://twitter.com/c18t>

=head1 Copyright and licence

Copyright (C) 2011, U=Cormorant L<u@chimata.org>.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

See L<http://dev.perl.org/licenses/artistic.html>
