consumer_key = "consumer_key"
consumer_secret = "consumer_secret"
db_name = ":memory:"
driver_name = "SQLite"
screen_name = "ucrawl_tweet"
token = "12345-token"
token_secret = "token_secret"
user_id = "12345"
